import { test, expect } from '@playwright/test'; 
test('registro', async ({ page }) => {
    await page.goto('https://buggy.justtestit.org/register');
    await page.getByRole('banner').getByRole('img').click({ timeout: 50000 });
    await page.getByLabel('Login').click({ timeout: 50000 });
    await page.getByLabel('Login').click({ timeout: 50000 });
    await page.getByLabel('Login').press('CapsLock');
    await page.getByLabel('Login').fill('D');
    await page.getByLabel('Login').press('CapsLock');
    await page.getByLabel('Login').fill('Hernandez2015');
    await page.getByLabel('First Name').click({ timeout: 50000 });
    await page.getByLabel('First Name').fill('camilo');
    await page.getByLabel('First Name').press('ArrowDown');
    await page.getByLabel('First Name').press('ArrowDown');
    await page.getByLabel('Last Name').click({ timeout: 50000 });
    await page.getByLabel('Last Name').fill('bermudez');
    await page.getByLabel('Password', { exact: true }).click({ timeout: 50000 });
    await page.getByLabel('Password', { exact: true }).fill('');
    await page.getByLabel('Password', { exact: true }).press('CapsLock');
    await page.getByLabel('Password', { exact: true }).fill('D');
    await page.getByLabel('Password', { exact: true }).press('CapsLock');
    await page.getByLabel('Password', { exact: true }).fill('Vale022414?');
    await page.getByLabel('Confirm Password').click({ timeout: 50000 });
    await page.getByLabel('Confirm Password').fill('D');
    await page.getByLabel('Confirm Password').press('CapsLock');
    await page.getByLabel('Confirm Password').fill('Vale022414?');
    await page.getByRole('button', { name: 'Register' }).click({ timeout: 50000 });
    await page.getByText('UsernameExistsException: User already exists').click({ timeout: 50000 });
  });