import { test, expect } from '@playwright/test'; 
test('registro', async ({ page }) => {
    await page.goto('https://buggy.justtestit.org/register');
    await page.getByRole('banner').getByRole('img').click({ timeout: 50000 });
    await page.getByLabel('Login').click({ timeout: 50000 });
    await page.getByLabel('Login').click({ timeout: 50000 });
    await page.getByLabel('Login').press('CapsLock');
    await page.getByLabel('Login').fill('D');
    await page.getByLabel('Login').press('CapsLock');
    await page.getByLabel('Login').fill('Hernandez2015');
    await page.getByLabel('First Name').click({ timeout: 50000 });
    await page.getByLabel('First Name').fill('camilo');
    await page.getByLabel('First Name').press('ArrowDown');
    await page.getByLabel('First Name').press('ArrowDown');
    await page.getByLabel('Last Name').click({ timeout: 50000 });
    await page.getByLabel('Last Name').fill('bermudez');
    await page.getByLabel('Password', { exact: true }).click({ timeout: 50000 });
    await page.getByLabel('Password', { exact: true }).fill('');
    await page.getByLabel('Password', { exact: true }).press('CapsLock');
    await page.getByLabel('Password', { exact: true }).fill('D');
    await page.getByLabel('Password', { exact: true }).press('CapsLock');
    await page.getByLabel('Password', { exact: true }).fill('Vale022414?');
    await page.getByLabel('Confirm Password').click({ timeout: 50000 });
    await page.getByLabel('Confirm Password').fill('D');
    await page.getByLabel('Confirm Password').press('CapsLock');
    await page.getByLabel('Confirm Password').fill('Vale022414?');
    await page.getByRole('button', { name: 'Register' }).click({ timeout: 50000 });
    await page.getByText('UsernameExistsException: User already exists').click({ timeout: 50000 });
  });
    test('login', async ({ page }) => {
      await page.goto('https://buggy.justtestit.org/register');
    await page.getByPlaceholder('Login').click();
    await page.getByPlaceholder('Login').fill('Hernandez2015');
    await page.getByRole('navigation').locator('input[name="password"]').click();
    await page.getByRole('navigation').locator('input[name="password"]').fill('Vale022414?');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByText('Hi, camilo').click();
  });
    test('edad', async ({ page }) => {
    await page.goto('https://buggy.justtestit.org/register');
    await page.getByPlaceholder('Login').click();
    await page.getByPlaceholder('Login').fill('Hernandez2015');
    await page.getByRole('navigation').locator('input[name="password"]').click();
    await page.getByRole('navigation').locator('input[name="password"]').fill('Vale022414?');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByRole('link', { name: 'Profile' }).click();
    await page.getByLabel('Age', { exact: true }).click();
    await page.getByLabel('Age', { exact: true }).fill('28');
    await page.getByRole('button', { name: 'Save' }).click();
  });